[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
verbosity = 3
evm_version = "paris"

remappings = ["forge-std/=lib/forge-std/src/", "@openzeppelin/=lib/openzeppelin-contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options